export const shoesData = [
  {
    imageSrc: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    name: "Nike Air Monarch IV",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "200",
    brand: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    name: "Nike Air Vapormax Plus",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "200",
    brand: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    imageSrc: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    name: "Nike Waffle One Sneaker",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "200",
    brand: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    name: "Nike Running Shoe",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "200",
    brand: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    name: "Flat Slip On Pumps",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "200",
    brand: "Vans",
    color: "green",
    category: "flats",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    name: "Knit Ballet Flat",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "50",
    brand: "Adidas",
    color: "black",
    category: "flats",
  },

  {
    imageSrc: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    name: "Loafer Flats",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "50",
    brand: "Vans",
    color: "white",
    category: "flats",
  },

  {
    imageSrc: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    name: "Nike Zoom Freak",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "200",
    brand: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    imageSrc: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    name: "Nike Men's Sneaker",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "200",
    brand: "Adidas",
    color: "blue",
    category: "sneakers",
  },

  {
    imageSrc: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    name: "PUMA BLACK-OCE",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "150",
    brand: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    name: "Pacer Future Sneaker",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "150",
    brand: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    name: "Unisex-Adult Super",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "150",
    brand: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    name: "Roma Basic Sneaker",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "150",
    brand: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    name: "Pacer Future Doubleknit",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "150",
    brand: "Puma",
    color: "black",
    category: "sneakers",
  },

  {
    imageSrc: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    name: "Fusion Evo Golf Shoe",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "100",
    brand: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    name: "Rainbow Chex Skate",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "100",
    brand: "Vans",
    color: "red",
    category: "flats",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    name: "Low-Top Trainers",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "100",
    brand: "Vans",
    color: "white",
    category: "sandals",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    name: "Vans Unisex Low-Top",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "100",
    brand: "Vans",
    color: "blue",
    category: "sandals",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    name: "Classic Bandana Sneakers",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "50",
    brand: "Nike",
    color: "black",
    category: "sandals",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    name: "Chunky High Heel",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "50",
    brand: "Vans",
    color: "black",
    category: "heels",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    name: "Slip On Stiletto High Heel",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "100",
    brand: "puma",
    color: "black",
    category: "heels",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    name: "DREAM PAIRS Court Shoes",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "150",
    brand: "Nike",
    color: "red",
    category: "heels",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    name: "Nike Air Vapormax Plus",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "200",
    brand: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    imageSrc: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    name: "Low Mid Block Heels",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "200",
    brand: "Nike",
    color: "black",
    category: "heels",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    name: "Chunky High Heel",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "50",
    brand: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    name: "Amore Fashion Stilettos",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "150",
    brand: "Adidas",
    color: "white",
    category: "heels",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    name: "Bridal Sandals Glitter",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "50",
    brand: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    imageSrc: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    name: "Wedding Prom Bridal",
    reviewCount: 123,
    oldPrice: 14000,
    newPrice: "50",
    brand: "Adidas",
    color: "black",
    category: "flats",
  },
];